language: node_js

sudo: required
dist: trusty
addons:
  chrome: stable

env:
  global:
  - SUPPRESS_NO_CONFIG_WARNING=true

cache:
  yarn: true
  directories:
  - node_modules

install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- yarn --pure-lockfile --ignore-engines
- npm rebuild node-sass

script:
  - yarn test

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
