language: node_js

sudo: required
dist: trusty
addons:
  chrome: stable

cache:
  yarn: true
  directories:
  - node_modules
  - $HOME/.cache # includes bowers cache

install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- yarn --prefer-offline --pure-lockfile
- ./node_modules/bower/bin/bower install --config.interactive=false

script:
- yarn test

